[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# 序列化规范
serde = { version = "1.0.106", features = ["derive"] }

# 编解码器
bincode = "1.2.1"

# 加密
rust-crypto = "0.2"
